# Generated by Django 5.0.2 on 2024-03-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_data',
            name='s_no',
            field=models.IntegerField(max_length=5),
        ),
    ]
