# Generated by Django 5.0.2 on 2024-03-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0003_alter_to_data_s_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_data',
            name='s_no',
            field=models.IntegerField(),
        ),
    ]
