# Generated by Django 5.0.2 on 2024-03-01 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0004_alter_to_data_s_no'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='to_data',
            table='to_data',
        ),
    ]
