# Generated by Django 5.0.2 on 2024-03-04 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0005_alter_to_data_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='to_data',
            table=None,
        ),
    ]
